version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-scripts/:/docker-entrypoint-initdb.d/

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - app
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db


volumes:
  dbdata: