# Stage 1
FROM node:18-alpine as builder

WORKDIR /app

RUN npm install drizzle-orm postgres tsx dotenv

# Stage 2
FROM node:18-alpine as runner

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY ./drizzle ./drizzle
COPY ./src/db ./src/db
COPY ./package.json ./

CMD ["npm", "run", "migrate"]
